name: Test C-mantic

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: "Test (${{ matrix.os }}, vscode-${{ matrix.code-version }})"
    runs-on: ${{ matrix.os }}

    # We want to run on external PRs, but not on internal PRs since they'll be run on push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        code-version: [stable, insiders]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup XVFB
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: NPM Install
      run: npm install

    - name: ESLint
      if: matrix.code-version == 'stable'
      run: npm run lint

    - name: Compile
      run: npm run compile && npm run compile-tests

    - name: Run Tests
      run: npm test
      env:
        CI: true
        ELECTRON_NO_ATTACH_CONSOLE: 1
        DISPLAY: ":99.0"
        CODE_VERSION: ${{ matrix.code-version }}
