name: Test C-mantic

# Controls when the action will run.
on:
  push:

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup XVFB
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

    - name: Setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: npm test
      run: npm test
      env:
        CI: true
        ELECTRON_NO_ATTACH_CONSOLE: 1
        DISPLAY: ":99.0"
